# Generated by Django 4.1.6 on 2023-06-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myamazonapp', '0005_customer_alter_address_customer_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
