# Generated by Django 4.1.6 on 2023-06-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myamazonapp', '0006_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default=9999999999),
        ),
    ]
