# Generated by Django 4.1.6 on 2023-06-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myamazonapp', '0009_remove_customer_mobile_remove_customer_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
