# Generated by Django 4.1.6 on 2023-07-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myamazonapp', '0011_product_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='TransactionId',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='cardnumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myamazonapp.customer'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='cvv_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='expiry',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
